apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore-ui
  annotations:
    github.com/project-slug: 'mlewis-portal-demo/petstore-ui'
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: team-a
  dependsOn:
    api:default/pets-api
    api:default/store-api
