apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore-ui
  annotations:
    github.com/project-slug: 'mlewis-portal-demo/petstore-ui'
spec:
  type: website
  lifecycle: production
  owner: team-a
